### ISSUE TITLE
[android] client needs an update

### ISSUE THREAD

**Issue by akallabeth** [FreeRDP/FreeRDP#11106]
Android client UI is old and does not conform to current android paradigms

It will be required to update the project and permissions stuff to current paradigms.

**Comment by akallabeth** [comment]
as a first step https://github.com/FreeRDP/FreeRDP/pull/11110 fixes crashing issues

**Comment by licaon-kter** [comment]
Nice, confirmed it builds and runs fine

**Comment by akallabeth** [comment]
@licaon-kter thx, merged the pr, so we have something that now not only compiles but also not crashes when starting 🎉 
only remainig thing is rewriting the android java/kotlin stuff to be less android 2.x 😁

**Comment by licaon-kter** [comment]
@akallabeth grep, do ping me when a release is ready to test

**Comment by akallabeth** [comment]
@licaon-kter ok, pinging you here (don´t have any other contact of you).
there is a new release 3.11.0 is available, but due to a few regressions a 3.11.1 will soon follow. (
anyway, the android related changes are in there so a new build should be possible.

**Comment by licaon-kter** [comment]
```
  - versionName: 3.11.0
    versionCode: 3011000
    commit: 4312666c8f89cb5464fc6e79423d1d7e33683ebe
    subdir: client/Android/Studio/aFreeRDP
    sudo:
      - apt-get update
      - apt-get install -y make pkg-config file libncurses5
    gradle:
      - yes
    rm:
      - client/Mac
      - client/Wayland
      - client/Windows
      - client/X11
      - client/iOS
    prebuild:
      - sed -i -e "/hasProperty('RELEASE/,+2d" -e '/println/d' ../build.gradle
      - sed -i -e 's/versionCode =.*/versionCode = $$VERCODE$$/' -e 's/versionName =.*/versionName = "$$VERSION$$"/' build.gradle
      - sdkmanager 'cmake;3.22.1'
    build:
      - cd ../../../..
      - scripts/android-build-freerdp.sh --ndk $$NDK$$ --sdk $$SDK$$ --openh264 --openh264-ndk
        $$NDK$$ --release
    ndk: 27.2.12479018
```

builds fine (will test functionality soon)

but, the APK is huge at ~147Mb

looking in the build log I see:
```
[CXX1104] NDK from ndk.dir at /opt/android-sdk/ndk/27.2.12479018 had version [27.2.12479018]
which disagrees with android.ndkVersion [27.0.12077973]
Unable to strip the following libraries, packaging them as they are:
libavcodec.so, libavutil.so, libcjson.so, libcrypto.so, libfreerdp-android.so, libfreerdp-client3.so, libfreerdp3.so, libopenh264.so, libssl.so, libswresample.so, libswscale.so, libwinpr3.so.
```

@akallabeth where does `27.0.12077973` come from? The only NDK reference that I see is: https://github.com/FreeRDP/FreeRDP/blob/3.11.1/client/Android/Studio/freeRDPCore/build.gradle#L17
