### ISSUE TITLE
F-Droid update

### ISSUE THREAD

**Issue by linsui** [FreeRDP/FreeRDP#9183]
@antenore Could you please take a look at https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13346? I tried to update it on F-Droid  but it seems it has some problem.

**Comment by akallabeth** [comment]
@linsui you might have a look at https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10678
I did not have time to read into the whole thing, so never completed that one.

**Comment by linsui** [comment]
Things changed a lot... 2.6.0 didn't build for us but 2.10 build without problem.

**Comment by linsui** [comment]
Yes, so --openh264-ndk is used now. And it seems the problem is not related to the native code since it doesn't install on my phone.

**Comment by akallabeth** [comment]
@linsui and the newer versions can be used (and therefore also all the `NDK` they support)

**Comment by akallabeth** [comment]
@linsui also, I´d recommend using the newest available `cmake

**Comment by linsui** [comment]
`AppIntegrityManagerServiceImpl: com.android.server.pm.PackageManagerException: /data/app/vmdl1520427379.tmp/base.apk (at Binary XML file line #110): com.freerdp.afreerdp.services.SessionRequestHandlerActivity: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present` on Android 13

**Comment by akallabeth** [comment]
@linsui the android client is quite old, so best set an older target API to resolve this.

**Comment by linsui** [comment]
It's set in https://github.com/FreeRDP/FreeRDP/blob/62b6c983937d5dbb6fac49d0a25f1c9a8fa6732e/client/Android/Studio/build.gradle#L23 . Do you mean we should override it? Which api should we set?

**Comment by akallabeth** [comment]
@linsui yes, you should override it with a properties file.
as for which `API`, you need to try which one introduced the changes in manifest requirements. (you may also create a pr for fixing the manifest issues, but that is another matter)

**Comment by linsui** [comment]
It's already fixed in https://github.com/FreeRDP/FreeRDP/commit/19297707e02b51a84ba45e4cc5740aa002d228c5.

**Comment by linsui** [comment]
MR merged.

**Comment by licaon-kter** [comment]
Can we reopen?

Trying to update to 3.10.3

recipe:
```
  - versionName: 3.10.3
    versionCode: 3010003
    commit: 1f168a62db864f7b676964ca3f399ec76a4ae91c
    subdir: client/Android/Studio/aFreeRDP
    sudo:
      - apt-get update
      - apt-get install -y make pkg-config wget file libncurses5
    gradle:
      - yes
    rm:
      - client/Mac
      - client/Wayland
      - client/Windows
      - client/X11
      - client/iOS
    prebuild:
      - sed -i -e '/androidGitVersion {/a format "%tag%"' -e 's/0.4.4/0.4.14/' build.gradle
      - sed -i -e '/hasProperty/,+2d' -e '/println/d' ../build.gradle
      - sed -i -e 's/wget/wget -q/' ../../../../scripts/android-build-common.sh
    build:
      - cd ../../../..
      - scripts/android-build-freerdp.sh --ndk $$NDK$$ --sdk $$SDK$$ --openh264 --openh264-ndk
        $$NDK$$ --release
    ndk: r25c
```

while I needed to bump this https://github.com/FreeRDP/FreeRDP/blob/3.10.3/client/Android/Studio/aFreeRDP/build.gradle#L2 to `0.4.14` as `0.4.4` was not found

it builds fine

yet, I'm missing `lib/arch/libc++_shared.so` and the app is stuck at a blank screen at start

I tried injecting `-DANDROID_STL=c++_shared` here: https://github.com/FreeRDP/FreeRDP/blob/3.10.3/client/Android/Studio/freeRDPCore/build.gradle#L46 and here https://github.com/FreeRDP/FreeRDP/blob/3.10.3/scripts/android-build-freerdp.sh#L111

and `c++_shared` here: https://github.com/FreeRDP/FreeRDP/blob/3.10.3/client/Android/Studio/freeRDPCore/src/main/cpp/CMakeLists.txt#L82

but none helped

any ideas?
